# Generated by Django 4.2.3 on 2023-07-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(max_length=10)),
                ('sname', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
