# Generated by Django 4.2.3 on 2023-07-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sname',
            new_name='studname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sno',
        ),
    ]
