# Generated by Django 4.2.3 on 2023-07-22 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_sname_student_studname_remove_student_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comments',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
