# Generated by Django 4.2.3 on 2023-07-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='comments',
        ),
    ]
